version: "3.7"

services:
  app:
    image: bmiwebcalculator:latest
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy  
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "0306"
      MYSQL_DB: ibiza

  mysql:
    image: mysql:5.7
    # volumes:
    #   - ibiza-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "0306"
      MYSQL_DATABASE: ibiza
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

# volumes:
#   ibiza-mysql-data:
